"""
Data models for conversation summarization and insights
"""

from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class ConversationSummary(BaseModel):
    """
    Summary of a conversation session
    Generated by Claude Haiku for cross-session recall
    """
    session_id: str = Field(..., description="Chat session ID")
    student_id: str = Field(..., description="Student ID")

    # Summary content
    topics_discussed: List[str] = Field(
        default_factory=list,
        description="Main topics covered in conversation"
    )
    key_questions: List[str] = Field(
        default_factory=list,
        description="Important questions asked by student"
    )
    concepts_explained: List[str] = Field(
        default_factory=list,
        description="Concepts that were explained"
    )
    areas_of_struggle: List[str] = Field(
        default_factory=list,
        description="Areas where student struggled"
    )

    # Structured summary
    summary_text: str = Field(
        ...,
        description="Free-form summary (2-3 sentences)"
    )

    # Metadata
    message_count: int = Field(
        ...,
        ge=0,
        description="Number of messages in session"
    )
    duration_seconds: int = Field(
        ...,
        ge=0,
        description="Session duration in seconds"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "session_id": "uuid",
                "student_id": "uuid",
                "topics_discussed": ["fractions", "division", "word problems"],
                "key_questions": [
                    "How do I divide fractions?",
                    "Why do we flip the second fraction?"
                ],
                "concepts_explained": [
                    "Division as inverse of multiplication",
                    "Keep-Change-Flip rule"
                ],
                "areas_of_struggle": ["Understanding reciprocals"],
                "summary_text": "Student learned about dividing fractions using the keep-change-flip method. Struggled with the concept of reciprocals but made progress.",
                "message_count": 15,
                "duration_seconds": 1200
            }
        }


class InsightExtraction(BaseModel):
    """
    Insights extracted from conversation patterns
    """
    student_id: str = Field(..., description="Student ID")

    # Learning patterns
    preferred_learning_style: Optional[str] = Field(
        None,
        description="Identified learning style (visual, verbal, example-based)"
    )
    engagement_level: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Engagement score (0-1)"
    )

    # Behavioral insights
    question_asking_frequency: str = Field(
        ...,
        description="How often student asks questions (low/medium/high)"
    )

    persistence_level: str = Field(
        ...,
        description="How persistent student is when struggling (low/medium/high)"
    )

    # Cognitive patterns
    common_misconceptions: List[str] = Field(
        default_factory=list,
        description="Recurring misconceptions identified"
    )

    strength_indicators: List[str] = Field(
        default_factory=list,
        description="Signs of strength or understanding"
    )

    # Recommendations
    recommended_interventions: List[str] = Field(
        default_factory=list,
        description="Suggested interventions for parent/teacher"
    )

    # Metadata
    sessions_analyzed: int = Field(
        ...,
        ge=1,
        description="Number of sessions analyzed"
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence in insights (0-1)"
    )
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "student_id": "uuid",
                "preferred_learning_style": "example-based",
                "engagement_level": 0.75,
                "question_asking_frequency": "medium",
                "persistence_level": "high",
                "common_misconceptions": [
                    "Confuses division and multiplication",
                    "Struggles with word problem interpretation"
                ],
                "strength_indicators": [
                    "Quick to grasp visual explanations",
                    "Self-corrects when given hints"
                ],
                "recommended_interventions": [
                    "Provide more visual diagrams",
                    "Use step-by-step worked examples"
                ],
                "sessions_analyzed": 5,
                "confidence": 0.8
            }
        }


class SnapshotTrigger(BaseModel):
    """
    Trigger for creating profile snapshot
    """
    student_id: str
    session_id: str
    reason: str = Field(
        ...,
        description="Reason for snapshot (completed_test, milestone_reached, etc.)"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)
